### ISSUE TITLE
Possible glitch with a versioning indicator in linux app

### ISSUE THREAD

**Issue by Gutalean** [idena-network/idena-desktop#112]
My linux app always stays 0.0.1 and I don't receive any update notifications. Is it ok to use it for validations? As for the node it is being updated regularly and with notifications.

**Comment by aidenaio** [comment]
hey @Gutalean 
thanks for reaching out 🙌 

the reason you always get `0.0.1` is the dev environment you use. there is not much sense to show a particular version as you may drift between branches and commits you're working on.

we do not recommend `npm start` for the validation purposes as we're not aware of the environment you use, thus issues you may have so cannot 💯 guarantee everything will go smooth.

also, we do not officially support any linux distro yet though start looking into it as we see growing demand.

in the meanwhile, the best option for you and all linux users will be building and packaging the app on your own. there is an `npm run dist` target for this. you may also put the version you want in `package.json` before building.

we also recommend building at tags only as those are the most stable versions 100% matching public release versions.

hope it helps and have a good day!

**Comment by Gutalean** [comment]
Thanks, I've built it into AppImage file and it started to work quicker.

**Comment by aidenaio** [comment]
Closing this

we started working towards linux builds as well #115
