### ISSUE TITLE
Absence of keywords for some flips during LongSession

### ISSUE THREAD

**Issue by Gutalean** [idena-network/idena-desktop#126]
During LongSession I have some flips without keywords. The app says that they are loading but nothing changes with time passes usually. What is the reason for this and what should I do with such flips? 
I guess I have 3 options: 
choose Both relevant
choose Report
choose Submit answers (w/o Relevant or Report button being pressed).

**Comment by Lovro007** [comment]
I had the same problem too.
I waited for them to load, and solve other flips that had keywords, then after couple of minutes came back to see if they showed up, but nothing.

**Comment by rioda-org** [comment]
That usualy happens to me also with flips made by Chinese users... don't know if that makes sense at all but that is what I've experienced...

**Comment by robertwebdev** [comment]
> So after a few sessions, I guess this can continue to be the situation more than a problem as we are probbably getting those words directly from a node that created those flips. 

I don't think it is working that way. Once you make a flip the complete data is sent to the blockchain - including keywords. For me the problem is on the Idena Client side - somewhere around getting data from Idena servers during validation process.

**Comment by rioda-org** [comment]
What Idena servers are you refering to?
Also to be clearer, I guess, we do not get words or flips, but rather keys to decrypt them from the nodes/identities that created them.

**Comment by robertwebdev** [comment]
Thanks for making it clear.
In the last validation on 20th March 3 last long session flips didn't load the keywords for me.

> And if the connection to them fail(they lose internet/power), you won't get those words nor flips. But those flips will not count in the validation score.

Unfortunately those count, have a look on my post https://github.com/idena-network/idena-desktop/issues/190#issuecomment-603808808

**Comment by robertwebdev** [comment]
Thanks for making it clear.
In my case 3 last long session flips didn't load the keywords during last long session on 20th March.

**Comment by midenaio** [comment]
Keywords are encrypted and not available during the short session. Keywords might be also not available during the long session if a person who made the flip does not take part in the validation session.

**Comment by KruciferX** [comment]
It's been a long time since last post, but why are flips shown while keywords for the same flips aren't if a person who made the flip doesn't take part in the validation session?

Aren't both flips (images) and keywords encrypted on node and decrypted only during validation session?

**Comment by midenaio** [comment]
Keywords for flip are provided together with the short answer submission. If a person who made the flip does not take part in the validation but keeps the node running then the flip will be available for other participants automatically without the keywords.

**Comment by csculley** [comment]
On this last epoch, I had 4 flips with missing keywords, and they were the first four flips to load. Could it also be that for initial flips perhaps, the overall congestion of the network caused these keywords not to load? I feel like these fears could be prevented with a simple button that can explicitly requery the network for the key words, or the flip content for that matter (I know some members have issues where the flip loading gets partially stuck).

**Comment by rioda-org** [comment]
It's just coincidence that they were 4 first flips... that just meant all from one node that probablly lost conection, went offline...
