### ISSUE TITLE
Flips not loaded in short session and my status goes down to "not validated"

### ISSUE THREAD

**Issue by luna-park** [idena-network/idena-desktop#190]
Hi, flips not loaded in short session. Log:
[idena_short.log](https://github.com/idena-network/idena-desktop/files/4363635/idena_short.log)

**Comment by jojo110033** [comment]
Hi team, i am also facing the same issue. Please find the details below
1. Client Log attached
2. Node log attached
3. Using local node on VPS
4. OS Detail :- Windows Server 2016
5. Issue - Short flip not loaded on 20th March flip session.
[Client Log.log](https://github.com/idena-network/idena-desktop/files/4380209/Client.Log.log)
[Node Log.log](https://github.com/idena-network/idena-desktop/files/4380210/Node.Log.log)

**Comment by robertwebdev** [comment]
I also confirm this issue. On 20th March last of my short session flip didn't load, as a result I got 5/6 Right answers 83.33%.

![1](https://user-images.githubusercontent.com/22289663/77535723-63b4c900-6e9b-11ea-85fc-e80e54f2c79e.png)
![2](https://user-images.githubusercontent.com/22289663/77535728-64e5f600-6e9b-11ea-9725-30f99f06d525.png)

**Comment by aidenaio** [comment]
hey hey,
thanks for details 👍 
investigating this 🔍

**Comment by aidenaio** [comment]
Flips key distribution was improved in the latest node releases. Please update

**Comment by Twitxx** [comment]
I'm currently doing the validation and I got 10 flips that won't load. What are we even supposed to do? I thought it was supposed to improve not get worse..
