### ISSUE TITLE
The app synchronized too slow

### ISSUE THREAD

**Issue by Gutalean** [idena-network/idena-desktop#191]
Hello!

One of my invitees didn't pass last validation because he didn't sync his app in time before the validation started despite the fact that he started syncing like an hour before it. At first syncing was ok, but towards the end it had slowed down significantly. Here is the screenshot of the moment:

![Untitled](https://user-images.githubusercontent.com/8298394/77234181-7db18b80-6bbd-11ea-9471-86e139c94452.png)

Please tell me if you need any log files for the further investigation. Windows 7, 64 bit.

**Comment by xxyqyq** [comment]
Please use connect to remote node for more connections and faster speed

**Comment by rioda-org** [comment]
We can see from the log screen above that something was using files that built-in node tried to use. Did he experiment with running remote local node and by any chance let it run also. This would explain message that files are in use by other process...

Log files would absolutely help, link speed down/up, and we can see that he is connected by Wi-Fi, lan cable is my absolute recomendation...
