### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by csculley** [idena-network/idena-desktop#192]
Hello,

As I was inspecting your repository, I noticed that there isn't a license specified in a file such as `LICENSE.md`. Adding a license will help with encouraging contributions, letting contributors know how their work will be distributed, as well as clarifying the process for redistributions (such as [mine on Arch Linux's AUR](https://aur.archlinux.org/packages/idena-desktop-git/), which just attempts to build from master).

Thanks!

**Comment by aidenaio** [comment]
Agree! Working on this

**Comment by aidenaio** [comment]
b9b9815
