### ISSUE TITLE
Flip making - Auto convert to jpg (suggestion)

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-desktop#206]
Hello, I've tested 0.7.2 version, editor is great :)
Wanted to see how the auto resize feature is working. I saw that pictures that have large resolution are resized to 440px width. Tested with some random png picture from the internet.
Then I wanted to see what was its size in kb. I copied base64 from flips.json to the html and made img, saved it to check it's size in kb.
Even in that resolution, **png had 263kb** and client allowed me to submit it.
When I converted it to **jpg, it had only 38kb**.

If there is a chance, maybe introduce some "auto convert to jpg" feature.

**Comment by midenaio** [comment]
Auto convert to jpeg is supported for the newly created flips: see compressedPics section in the flips.json file

**Comment by rioda-org** [comment]
Sorry, missed that... This is great 240x180px JPG 9kb... Perfect
