### ISSUE TITLE
Suggestion: low report barrier for a bad flip from 66% to 33% or at least 50%

### ISSUE THREAD

**Issue by Gutalean** [idena-network/idena-desktop#214]
Bad flips are everywhere nowadays. They put everybody's score in danger of being randomly and
unfairly lowered. You can be even killed by a bad flip. At any given epoch the network contain around 50% of newbies who are afraid to report bad flips cause they don't sure if it is right thing to do and that it won't backfire on them somehow. So, in my opinion the good way to mitigate that problem would be lowering the report barrier for a flip from current 66% of a committee members  to 33% or at least 50%. Otherwise there is no motivation to create good flips - you'll get your reward unconditionally. Though, you still need a way to somehow punish guys who report all flips they see just for fun.

**Comment by Gutalean** [comment]
I'll add here that for motivating people to take flips curation seriously we can enforce theses rules:
1) If a flip is considered by a committee as a bad one and a member of this committee reported it then he gets a reward, otherwise the person doesn't get any reward.
2) If a flip is considered by a committee as a good one and a member of this committee didn't report it then he gets a reward, otherwise the person doesn't get any reward.
This will work only in combination with the previous suggestion of lowering the barrier to 33%.

**Comment by midenaio** [comment]
The barrier is to be lowered to 50% in the upcoming fork:
https://medium.com/idena/idena-hard-fork-announcement-8271b7fc9b0c
