### ISSUE TITLE
Suggestion for blockchain and wallet : Add a Note/ Memo like Stellar

### ISSUE THREAD

**Issue by codev911** [idena-network/idena-desktop#226]
I have an sugestion for idena blockchain, i hope you hear my suggestion, because an people if want create some exchange may helped get verified wallet

**Comment by rioda-org** [comment]
No exchanges are yet planned, at least not before we get through experimental mainnet phase. I'm sure multiwallet option will be implemented as soon as devs think we have stable version.

**Comment by andridevk911** [comment]
ok, i will closed it
