### ISSUE TITLE
short session time with bad flips - request to extend to 3 minutes by adding additional 2 M 

### ISSUE THREAD

**Issue by Mozdalifa178** [idena-network/idena-desktop#228]
Hi idena lovers and Development team 

I suggest to increase the short session timing by adding additional two minutes in case there is a bad flips appear so you have more time to think ,,that definitely will affect all candidate and newbies even verified identities .humans has nothing to do with short session even they can skip it . 
in short words : 
- Extend short session by + 2 minutes 
- Reduce long session timing to 16 minutes . 
I am an affected newbie failed in a short session due to bad flips with almost 97 % in long session 
Please support . 
Thanks

**Comment by rioda-org** [comment]
My opinion is that right now, you are in mercy of flip lottery wich will get you bad or good flips. By extending short session, people who again get bad flips will also fail, and people who get good flips will be able to solve 4-5 nodes.
This is temporary matter before we find a way to deal with lousy flip makers...
