### ISSUE TITLE
create preparation section before validation

### ISSUE THREAD

**Issue by andridevk911** [idena-network/idena-desktop#229]
hi there, i have more suggestion for idena wallet before validation section started, please add some preparation section before validation start for improve lag. My suggestion is lock / deny blockchain transaction like Send DNA, Create & Submit Flips and Activate invite code will locked in 5 Minutes before validation section start. Because i got some problem in my node before, blockheight increase significant before validation start and make my node down. I hope my suggestion will readed and understandly, thanks

**Comment by Endogen** [comment]
Something like that is already in place. I've read a commit message that stated that some transaction types are not possible anymore to be sent at validation time. So that would be what you wanted.

**Comment by andridevk911** [comment]
of course, it would be better to lock the active transaction in 5 minutes or more before validation starts, it really helps to overcome lag and suppress the increase in blockheight before validation.

**Comment by andridevk911** [comment]
it would be better in the wallet application to be locked for transactions too before validation.

**Comment by aidenaio** [comment]
It doesn't seem correct to just lock all the transactions N mins before the validation. I got your point but it's not a priority now.
