### ISSUE TITLE
how to run testnet for test the wallet

### ISSUE THREAD

**Issue by olympicgame** [idena-network/idena-desktop#254]
how to run testnet for test the wallet? could anyone help to doc it please?

**Comment by jugi1** [comment]
No testnet yet, but there are some discussions about it.

**Comment by aidenaio** [comment]
could you plz elaborate on this

what is your more precise use-case? do you want to interconnect a bunch of nodes into your own home network or you want a fair testnet? just playing around or want something specific

though it's pretty the same tech side but very different tasks from the upper view. so plz give us more info to tackle it right 🙏 ℹ️

**Comment by aidenaio** [comment]
ok, in short

you need to specify _P2P_ and _IpfsConf_ sections properly in your `config.json`

```
"P2P": {
    "BootstrapNodes": []
  },
  "IpfsConf": {
    "BootNodes": []
  },
```

Next, run the node with `--config=config.json` and do not forget to specify the **same genesis block for each of your nodes**, like this

```
"GenesisConf": {
    "GodAddress": "0x0000000000000000000000000000000000000000",
    "FirstCeremonyTime": 1587577904
  },
```
Important, _GenesisConf_ should be **exactly the same** across all your testnet nodes.

Please check https://github.com/idena-network/idena-go#json-config as well.

Hope it helps!
