### ISSUE TITLE
Creating flips using one PC with a client which uses 2 remote nodes in rotation

### ISSUE THREAD

**Issue by darkblaze69** [idena-network/idena-desktop#255]
1. Have 2 remote nodes (A and B) which both have tasks to create 3 flips.
2. Launched client with connection to node A with it's API key.
3. Created and submitted a flip and closed client with connection to node A.
4. Launched client with connection to node B with it's API key.

Now I see that node B's task is only 2 flips left and 1st flip is from the node A.

Client version: 0.8.3
Node version: 0.19.1

**Comment by KruciferX** [comment]
Client keeps record of created flips locally, no matter to what node you connect.

**Comment by aidenaio** [comment]
yep the client knows of its local flips only

sync is something to consider in the next steps

**Comment by darkblaze69** [comment]
As a workaround for the issue - juggling with flips.json helps. Just backup / copy /paste flip objects inside this file.
