### ISSUE TITLE
NSFW words

### ISSUE THREAD

**Issue by jugi1** [idena-network/idena-desktop#257]
There is issue with some words that can be used for making NSFW flips.
Few examples: 
{name: '**rape**', desc: 'rape, violation, assault, ravishment'},
{name: '**orgy**', desc: 'orgy, debauchery, saturnalia, bacchanal, riot'}

We know some kids and religious people may can be affected and report flips.

**Comment by bingbinglee** [comment]
100% agree with this.

**Comment by aidenaio** [comment]
ref https://github.com/idena-network/idena-desktop/issues/263

**Comment by midenaio** [comment]
Any words can be used for making NSFW flips if someone wants to do it. 
To be mitigated by using a nude detection filter both for the flip submission and validation session.
