### ISSUE TITLE
Human invites bug

### ISSUE THREAD

**Issue by KruciferX** [idena-network/idena-desktop#259]
When client with Human status creates both invites in succession, both invitation codes are the same.
If a user changes tab in menu and comes back to Contacts to create second invite, invitation code changes as it should.

**Comment by rioda-org** [comment]
Just to add, after fiddling a bit, when you open invites.json, codes are visible there... gui just does not refresh in some cases... This was not universal thing with all clients just for some. If it happens again, we'll try to get logs..

**Comment by aidenaio** [comment]
hey,

yes, this is an issue we also caught internally.

here's the fix https://github.com/idena-network/idena-desktop/pull/267
