### ISSUE TITLE
Better flip shuffle

### ISSUE THREAD

**Issue by KruciferX** [idena-network/idena-desktop#262]
Since many submitted flips have the same image either as a starting one or an ending one on both sides, which can lead to some confusion with bad flips, I suggest that client disables putting first image on the left as first image on the right and last image on the left as last image on the right, so that with flip order of 1, 2, 3, 4, the shuffled side cannot be 1, X, X, X nor X, X, X, 4.

**Comment by midenaio** [comment]
The most secure flips usually have the same 4th image which is hard for AI to solve them. Flips that lead to confusion can not reach consensus during the long session and are being disqualified. Disqualified flips are not counted for the short session.
