### ISSUE TITLE
Short session submission error - possible hotfix

### ISSUE THREAD

**Issue by KruciferX** [idena-network/idena-desktop#265]
If during validation client somehow "freezes", it cannot submit short session answers, leaving user with failed validation.

Possible hotfix is "resetting" client if combination of following events happens (if time left allows it):

![Client log 1](https://user-images.githubusercontent.com/52136297/79068127-d9ef6300-7cc4-11ea-8bea-4f95bec6e114.png)

Cause at the same time, node was running just fine with 18 peers, so it's not a problem with node:

![Node log 1](https://user-images.githubusercontent.com/52136297/79068112-98f74e80-7cc4-11ea-85d0-7e07c5eb776d.png)

After client restart, ceremony moved forward but it was too late for short session answers:

![Client log 2](https://user-images.githubusercontent.com/52136297/79068173-36eb1900-7cc5-11ea-841e-a00e81980793.png)

![Node log 2](https://user-images.githubusercontent.com/52136297/79068193-6568f400-7cc5-11ea-96b2-8898c235bc51.png)

**Comment by aidenaio** [comment]
yep. sort of weird

but we do try to handle those edge cases. you may see _Retry_ button in the client plus the client fully persisting the validation routine.

Could you plz provide us logs so we can look into it to address the issue properly?

Thx

**Comment by KruciferX** [comment]
Sure thing. Here they are.

[Client.log](https://github.com/idena-network/idena-desktop/files/4503588/Client.log)

[Node.log](https://github.com/idena-network/idena-desktop/files/4503592/Node.log)

**Comment by aidenaio** [comment]
thanks
