### ISSUE TITLE
Prevent changing vote in long session after keywords show up

### ISSUE THREAD

**Issue by KruciferX** [idena-network/idena-desktop#270]
We're noticing that many flips get a strong consensus in long sessions, but people keep failing them in short. That's because in long sessions you have a lot of time to figure out bad flips and you also get to change your vote AFTER you see the keywords.
The fact that you can change your vote once you know the words allows more weak or even no consensus flips to get strong consensus.
Keeping the process in two steps (first vote, then report) is good, but only while not allowing to change your vote at step two.
Another option would be to show words in short sessions so challenged identities have at least a small chance to pass very bad flips that eventually make sense with words known and as a result get a consensus.

**Comment by Gutalean** [comment]
I agree with this suggestion. My own score for longsessions is much higher than that for shortsessions.

**Comment by KruciferX** [comment]
What does a label 'discussion' imply?
Where to discuss this?

**Comment by aidenaio** [comment]
pls up a topic under Discussion section if you're still interested in it.

closing this
