### ISSUE TITLE
Distribute key words for next epoch allready during long session of running validation 

### ISSUE THREAD

**Issue by ubiubi18** [idena-network/idena-desktop#274]
I am usually finished within 6-8 Minutes with short session as well as long session -  and now i would like to start making new flips allready, while long session is still running. I wonder if it could be possible to change protocol that way that new keywords for next epoch are allready generated and distributed after short session during long session? I guess many newbies will make the mistake to create flips during that time anyway and get frustrated later when they realise that it was wasted effort.

**Comment by ubiubi18** [comment]
there you go: i forgot doing the flips before todays ceremony ;) I ll give idena a break

**Comment by midenaio** [comment]
Keywords are generated randomly based on the last epoch block where a new list of identities is calculated for the next epoch. Theoretically it's possible to change that behavior however it will take significant protocol changes (Idena node changes are required).
