### ISSUE TITLE
Educational Widget for explaining what is a good flip

### ISSUE THREAD

**Issue by bingbinglee** [idena-network/idena-desktop#277]
A trigger captioning "What is a good flip?" 
![Artboard1](https://user-images.githubusercontent.com/62775041/80325973-4ca02880-8805-11ea-8cfd-fe5579b8c94d.png)

Which triggers the overlay shown below
![Artboard](https://user-images.githubusercontent.com/62775041/80325983-53c73680-8805-11ea-8162-d9c14732e1ce.png)

--
Will you be open to considering if the community sends this add into the desktop client via PR?

**Comment by jugi1** [comment]
I fully support this proposal, and it is easy to add it.

**Comment by bingbinglee** [comment]
@aidenaio would love your feedback.

**Comment by Syd-ai** [comment]
+10000

I think this kind of thing could also be implmented during the keyword check phase to have a clear "when to report" rules set. I don't feel the conditions of flip report appearing with a tooltip is visually enough and intuitive.

**Comment by midenaio** [comment]
It would be nice to have examples illustrating bad and good flips

![image](https://user-images.githubusercontent.com/47352542/81422960-2cf5f200-916d-11ea-96d8-698b626803f2.png)
![image](https://user-images.githubusercontent.com/47352542/81423001-3f702b80-916d-11ea-95bb-201e04e1275e.png)

**Comment by bingbinglee** [comment]
This is even better ofcourse :) , Given that you already showed a high-fidelity mockup - is this something being worked on @midenaio 😄

**Comment by midenaio** [comment]
@bingbinglee No, it's just a mockup yet

**Comment by jugi1** [comment]
Looks good.

**Comment by aidenaio** [comment]
we have What is a bad flip explainer now #593
