### ISSUE TITLE
Firefox incompatibility for idena sign-in

### ISSUE THREAD

**Issue by bingbinglee** [idena-network/idena-desktop#286]
Seems like all webkit based browsers work to open idena-client and handle callback.
Firefox, however, throws off this error:

![unknown](https://user-images.githubusercontent.com/62775041/81033914-552adb80-8e63-11ea-9d5c-904ee5fb2122.png)

**Comment by busimus** [comment]
Works perfectly in Firefox for me.
(Firefox version 75.0, OS is Linux)

**Comment by ProjXDev** [comment]
Doesn't work for me 🤔 (ubuntu 19 , firefox)

**Comment by busimus** [comment]
@ProjXDev Do you get the same error as the screenshot or does the Idena app launch but not do anything?
For the former, I'm not sure what to tell you. I never had this error on my main Arch desktop, didn't have it when I installed Idena on a clean Ubuntu 20.04 VM to test it.
For the latter, there's #287

**Comment by ProjXDev** [comment]
It opens and nothing happens

**Comment by bingbinglee** [comment]
Seems like this was a one-off and not really reproducible. Closing.
