### ISSUE TITLE
Check/sync time of client and warn if remote node is not in sync with it

### ISSUE THREAD

**Issue by KruciferX** [idena-network/idena-desktop#303]
A user failed his/her validation cause short session was 'missing'.

Logs show that client was 19 seconds behind node, so even though client submitted short answers 16 seconds before deadline, node sent the 'short answers submitting request' 3 seconds after the deadline.

Our suggestion is that client checks/syncs time with remote time server and (for remote nodes), also warns if node time is out of sync with client updated time (local nodes will already be in-sync with client).

**Comment by rioda-org** [comment]
https://scan.idena.io/identity/0x52dfb4babbf413a48e3daff85c2e1a3506cbc858/epoch/45/validation

Attached logs are stripped to validation time:
[logs.zip](https://github.com/idena-network/idena-desktop/files/4645432/logs.zip)

**Comment by aidenaio** [comment]
should be done soon
