### ISSUE TITLE
Suggestion: filter google images by usage right

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-desktop#316]
Currently when using the google feature to get images there is a warning on the bottom:

![Selection_558](https://user-images.githubusercontent.com/111600/83326965-96eb4e00-a278-11ea-910f-060435ddc319.png)

IMHO this makes this feature useless as how should I check the usage rights in this view. Ideally this picker would already filter for the correct rights like when using the web search:

![Selection_559](https://user-images.githubusercontent.com/111600/83326993-e467bb00-a278-11ea-8c72-b2ab8ba5219c.png)

So then also this warning could be removed and it would be much easier to create flips

**Comment by midenaio** [comment]
Image picker with a warning on the bottom is deprecated and will be closed by google soon. Duckduckgo search will be used instead. Feel free to reopen the issue if needed.
