### ISSUE TITLE
Suggestion: UI should reflect you can only submit flips after the first validation

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-desktop#317]
The UI is quite confusing there. It allows to create flips - but the submit screen does not allow to submit. This is ok but it should state why it is not possible to submit - currently this is very confusing for new users.

**Comment by jugi1** [comment]
I agree that lot of things need to be improved here

**Comment by midenaio** [comment]
It has been implemented as following:
![image](https://user-images.githubusercontent.com/47352542/87702066-5b69fc00-c7b2-11ea-8c73-692ad4227968.png)
