### ISSUE TITLE
Suggestion: Reporting should mention unclear flips

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-desktop#318]
I asked in the chat and people told me that I should report unclear flips - but it is not mentioned here:

![Idena_564](https://user-images.githubusercontent.com/111600/83330555-f739ba00-a28f-11ea-9626-4a7cbfaa7cf0.png)

also not clear what the "also" means here. I think this list should mention all conditions when one should report

**Comment by KruciferX** [comment]
"Also" means, on top of the original reason: "Are both keywords relevant to the flip?".

And I think that list should always be visible, not only on hover of report button with mouse.

As for unclear flips, dev team feels that bad flips won't get consensus. But that didn't prove to be true. What is totally illogical in short session becomes logical in long session with known keywords, affecting short session score.
