### ISSUE TITLE
Idena sign-in stopped working after HF (or client update)

### ISSUE THREAD

**Issue by KruciferX** [idena-network/idena-desktop#332]
After trying to sign in with client, following error occurs:

![image](https://user-images.githubusercontent.com/52136297/83949580-fde2a700-a824-11ea-9a60-2479959692c9.png)

**Comment by Gutalean** [comment]
Same here. I have Manjaro Linux.
![image](https://user-images.githubusercontent.com/8298394/83951663-cfbc9180-a83b-11ea-97fe-127f61685678.png)

**Comment by KruciferX** [comment]
I just got the info that old client (0.10.0) works fine.

**Comment by idenatoday** [comment]
Same here:
Client 0.10.0 was working when connected on old 0.20.0 node.
Not working anymore connected to 0.21.0 node.
Reason: Recovered address does not match anymore.

**Comment by bingbinglee** [comment]
same here

**Comment by Endogen** [comment]
same here

**Comment by bingbinglee** [comment]
@KruciferX does this work on an old client but a new node? If that is the case then its the client issue than the node issue?

**Comment by midenaio** [comment]
[Sign-in with Idena](https://github.com/idena-network/idena-desktop/wiki/DNA-url) protocol was changed due to the protobuf migration. 
Blockchain explorer has [been updated](https://github.com/idena-network/idena-explorer/pull/23). 
Sorry for the hassle
