### ISSUE TITLE
Client states that "flip size is too big"

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-desktop#342]
Win 10, after updating client to 0.13.1 while trying to submit flip, i got toast:
"flip is too big, max expected size 614400, actual 767817"
I have 4 jpg images all sum up to 40kb, they are attached. I have added them from my PC. Did not try add from google or paste image.
Client log shows nothing interesting. I have tried deleting flips.json and submitting again, got same message.

[images.zip](https://github.com/idena-network/idena-desktop/files/4821968/images.zip)

**Comment by jugi1** [comment]
I also tried to delete flips.json and I got blank flip screen
![s 7](https://user-images.githubusercontent.com/23556919/85468262-821a8580-b5ac-11ea-9dd5-f5a7ab2c5bd1.jpg)

**Comment by aidenaio** [comment]
fixed here https://github.com/idena-network/idena-desktop/pull/343
