### ISSUE TITLE
Latest update BUG

### ISSUE THREAD

**Issue by jugi1** [idena-network/idena-desktop#344]
Latest client updates  0.13.1 and 0.13.2 are not good and have bugs.
Lot of people reporting issues and not being able to send flips.

Renaming or deleting flips.json is not working.

 "Cannot read property 'every' of undefined" with 0.13.2

![image](https://user-images.githubusercontent.com/23556919/85532189-c7bc6a00-b60f-11ea-9436-071c9b4a558f.png)

![image](https://user-images.githubusercontent.com/23556919/85532334-e884bf80-b60f-11ea-8dfc-c8e7b9dab4c6.png)

**Comment by aidenaio** [comment]
fixed #345
