### ISSUE TITLE
URGENT - Can't submit/make flips after recent updates!

### ISSUE THREAD

**Issue by jugi1** [idena-network/idena-desktop#350]
Many people are reporting issue when they want to maek or submit flips.
Is there any real solution for them.
Fresh install is not working
Started to happen after client version 0.13.2 and 0.13.3

One of the LOG file by member: 
[log file.txt](https://github.com/idena-network/idena-desktop/files/4853560/log.file.txt)

https://t.me/IdenaNetworkPublic/91632
https://t.me/IdenaNetworkPublic/91485
https://t.me/IdenaNetworkPublic/91400
https://t.me/IdenaNetworkPublic/91153
https://t.me/IdenaNetworkPublic/91100

![image](https://user-images.githubusercontent.com/23556919/86156930-f0a89780-bb06-11ea-887d-360811eb2bf9.png)

![image](https://user-images.githubusercontent.com/23556919/86157378-9a882400-bb07-11ea-9b33-075af32a015d.png)

![image](https://user-images.githubusercontent.com/23556919/86157554-dcb16580-bb07-11ea-84ae-63fa47f72a63.png)

![image](https://user-images.githubusercontent.com/23556919/86157696-12eee500-bb08-11ea-906c-b77dcf8772ad.png)

**Comment by rioda-org** [comment]
Logs would help :D

**Comment by rioda-org** [comment]
I got some logs...
[logs.txt](https://github.com/idena-network/idena-desktop/files/4853551/logs.txt)

**Comment by aidenaio** [comment]
thanks! on this

**Comment by aidenaio** [comment]
I think I've found the issue.

Somehow, the locale is `undefined` at some clients/machines, or not properly initialized (yet 🤔 ). Wow, bummer!

This is totally unexpected thus an unhandled exception.

Fix soon.

Ok, let me think wha

**Comment by aidenaio** [comment]
thanks for the logs 🤜 🤛

**Comment by jugi1** [comment]
All candidates now have this screen and can't make any flips

![image](https://user-images.githubusercontent.com/23556919/86398078-516dd680-bca5-11ea-95c3-53cb142cab0c.png)

Temporary workaround is made by Krucifer (save as .json file)

```
{
	"flips": [
		{
			"id": " ",
			"pics": [
				"data:image/png;base64,iV",
				"data:image/png;base64,iV",
				"data:image/png;base64,iV",
				"data:image/png;base64,iV"
			],
			"compressedPics": [
				"data:image/jpeg;base64,/9j",
				"data:image/jpeg;base64,/9j",
				"data:image/jpeg;base64,/9j",
				"data:image/jpeg;base64,/9j"
			],
			"editorIndexes": [
				0,
				1,
				2,
				3
			],
			"nonSensePic": " ",
			"nonSenseOrder": -1,
			"order": [
				1,
				3,
				2,
				0
			],
			"hint": {
				"id": 0,
				"words": [
					{
						"name": " ",
						"desc": ""
					},
					{
						"name": " ",
						"desc": " "
					}
				]
			},
			"type": "archived",
			"createdAt": 1590500615847,
			"modifiedAt": 1590586862988
		}
	]
}
```

**Comment by rioda-org** [comment]
That message is adequate, why would candidates need to make flips? It was confusing previously when they start making flips and they don't need to.

**Comment by jugi1** [comment]
> That message is adequate, why would candidates need to make flips? It was confusing previously when they start making flips and they don't need to.

It is NOT adequate as I tested it with fresh client.
It is not about message but about the fact that you can NOT make flip.
Sending is not the issue.

**Comment by rioda-org** [comment]
Oh, yeah you are right, submit...

**Comment by aidenaio** [comment]
> I think I've found the issue.
> 
> Somehow, the locale is `undefined` at some clients/machines, or not properly initialized (yet 🤔 ). Bummer!
> 
> This is totally unexpected thus an unhandled exception.
> 
> Fix soon.

just merged it
release soon

**Comment by aidenaio** [comment]
> > That message is adequate, why would candidates need to make flips? It was confusing previously when they start making flips and they don't need to.
> 
> It is NOT adequate as I tested it with fresh client.
> It is not about message but about the fact that you can NOT make flip.
> Submit flip is not the issue, and that is what message is showing, along with missing **Add flip** button
> 
> PS
> Candidates make flips all the time for invitations.

you're right
that was missed :( moved to #356
