### ISSUE TITLE
All candidates can't make any flips

### ISSUE THREAD

**Issue by aidenaio** [idena-network/idena-desktop#356]
All candidates now have this screen and can't make any flips

![image](https://user-images.githubusercontent.com/23556919/86398078-516dd680-bca5-11ea-95c3-53cb142cab0c.png)

https://t.me/IdenaNetworkPublic/92098
Temporary workaround is made by Krucifer (save as .json file)

```
{
	"flips": [
		{
			"id": " ",
			"pics": [
				"data:image/png;base64,iV",
				"data:image/png;base64,iV",
				"data:image/png;base64,iV",
				"data:image/png;base64,iV"
			],
			"compressedPics": [
				"data:image/jpeg;base64,/9j",
				"data:image/jpeg;base64,/9j",
				"data:image/jpeg;base64,/9j",
				"data:image/jpeg;base64,/9j"
			],
			"editorIndexes": [
				0,
				1,
				2,
				3
			],
			"nonSensePic": " ",
			"nonSenseOrder": -1,
			"order": [
				1,
				3,
				2,
				0
			],
			"hint": {
				"id": 0,
				"words": [
					{
						"name": " ",
						"desc": ""
					},
					{
						"name": " ",
						"desc": " "
					}
				]
			},
			"type": "archived",
			"createdAt": 1590500615847,
			"modifiedAt": 1590586862988
		}
	]
}
```

_Originally posted by @jugi1 in https://github.com/idena-network/idena-desktop/issues/350#issuecomment-653167782_

**Comment by aidenaio** [comment]
sorted ab1ad460234af718f4a0f093392feb939aadf162

**Comment by jugi1** [comment]
workaround:
![s 7](https://user-images.githubusercontent.com/23556919/86469158-26cd5d80-bd39-11ea-8958-d77cfb298226.jpg)
