### ISSUE TITLE
IMPORTANT - Closed client/node testing before public release!

### ISSUE THREAD

**Issue by jugi1** [idena-network/idena-desktop#362]
We really need closed client/node testing before public release.
Many releases have some stupid bugs.

Issue with latest release:
**- Clicking on view flip crashes the client**
format of the flips is changed, but no reformat or wipe for old entries!
more detials: https://github.com/idena-network/idena-desktop/issues/361

--------------------------
**PROPOSITION:**
Closed group of smart technical members like Busimus, Mahmoud etc. test releases before main release!

**Comment by busimus** [comment]
No need for "closed" testing -- nothing is stopping you from testing each commit yourself. But regardless, it's not productive to do this until the code stabilizes. Automated testing should (and does) check the critical parts like the validation ceremony, the rest doesn't really matter right now.

**Comment by KruciferX** [comment]
> No need for "closed" testing -- nothing is stopping you from testing each commit yourself. But regardless, it's not productive to do this until the code stabilizes. Automated testing should (and does) check the critical parts like the validation ceremony, the rest doesn't really matter right now.

It does when error prevents users to create flips for that same validation ceremony.
It's not the case with this latest release, but it was with previous two releases.

**Comment by jugi1** [comment]
> No need for "closed" testing -- nothing is stopping you from testing each commit yourself. But regardless, it's not productive to do this until the code stabilizes. Automated testing should (and does) check the critical parts like the validation ceremony, the rest doesn't really matter right now.

Explain that to many people that complain in Telegram and Discord.
