### ISSUE TITLE
BUG during validation?

### ISSUE THREAD

**Issue by jugi1** [idena-network/idena-desktop#367]
One member recorded validation.
He passed it but was not validated, and late submission

![image](https://user-images.githubusercontent.com/23556919/86536107-56b96400-bee5-11ea-9aaa-eb44892fec60.png)

https://scan.idena.io/identity/0x260ffe0365237b799b82cbed5bc3cb54c91507bf

VIDEO (in russian):
https://www.loom.com/share/482b4910a0904da3814468915fc28d76

**Comment by midenaio** [comment]
Could you attach the client log file:
%appdata%/Idena/logs/idena.log

**Comment by jugi1** [comment]
> Could you attach the client log file:
> %appdata%/Idena/logs/idena.log

He did not want to share or send his log file

**Comment by midenaio** [comment]
> He did not want to share or send his log file

Okay. Then closing the issue
