### ISSUE TITLE
Syndrael - validation problem

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-desktop#373]
I'm Human status but today Short session didn't start for me. There was a blue message at the top and a countdown and a validate Button but nothing happened. I pushed Validate button but nothing.
Here are error message if it may help you.

[syndrael.zip](https://github.com/idena-network/idena-desktop/files/4880313/syndrael.zip)

![idena](https://user-images.githubusercontent.com/37978870/86620132-1ed12000-bfbc-11ea-8b94-a226f6272f4f.png)

VPS on Contabo
to launch my client: cd ~/Documents/idena/idena-desktop && npm start run
it was like freezing when short session started
Npm wallet on linux seems working but not to start short session for me
i started validation last year, i always validate with NPM client.
i'm on Debian

Client on linux installed. Fingers crossed. I hope i'll get an invitation in the next weeks
If it may help me. There is an error on Debian installation, but it works.
sudo dpkg -i idena-client-linux-0.14.2.deb 
[sudo] password for syndrael: 
Selecting previously unselected package idena-desktop.
(Reading database ... 274174 files and directories currently installed.)
Preparing to unpack idena-client-linux-0.14.2.deb ...
Unpacking idena-desktop (0.14.2-1036) ...
Setting up idena-desktop (0.14.2-1036) ...
Error in file "/usr/share/applications/evince.desktop": "" is an invalid MIME type ("" does not contain a subtype)
Processing triggers for gnome-menus (3.13.3-9) ...
Processing triggers for desktop-file-utils (0.23-1) ...
Processing triggers for mime-support (3.60) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...

**Comment by midenaio** [comment]
> to launch my client: cd ~/Documents/idena/idena-desktop && npm start run

We do not recommend to start the client with `npm start run` for the validation session.

Please download and run the [latest app version for linux](https://github.com/idena-network/idena-desktop/releases) or use `npm run dist` for building and packaging the app on your own.

You can also check https://github.com/idena-network/idena-desktop/issues/112
