### ISSUE TITLE
Cosmetic - Display "Next validation" time in local time

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-desktop#385]
On My Idena page, validation time is not displayed in local time in the right part of the window

![image](https://user-images.githubusercontent.com/37978870/87856216-e3204980-c91d-11ea-9986-7ae2329264a4.png)

**Comment by jugi1** [comment]
it is GMT time on right side
**G**reenwich **Mean** **T**ime

**Comment by aidenaio** [comment]
Thanks for spotting this!
