### ISSUE TITLE
Suggestion: Warning message for Newbies before submitting flip (bad flip, report/deletion fee)

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-desktop#397]
Hello,

Lot of Newbies are having issues where they submit flip but they want to change it afterwards. Then when they try to delete it, they often don't have enough balance to pay for deletion fee.
Other thing is that they don't know that, if flip is not good enough it can be reported and they will lose all their validation rewards.

My suggestion would be to introduce one warning mesage, for Newbies, when they hit submit flip button, something like this:
(native english speakers please suggest better phrasing)

**Are you sure that you want to submit this flip?**
- If this flip is not good enough, there is a chance that your flip will be reported and you will lose your validation rewards.
- The cost of deleting filp is aproximatly ____ DNA.

Can flip deletion fee be calculated aproximatly and placed up there?
I guess this way we can raise awareness about needed flip quality.

**Comment by KruciferX** [comment]
Very nice. 👍

**Comment by slavko989** [comment]
**I would like to see this! Looks good!**

**Comment by slavko989** [comment]
> My suggestion would be to introduce one warning mesage, for Newbies, when they hit submit flip button, something like this:
> (native english speakers please suggest better phrasing)
> 
> **Are you sure that you want to submit this flip?**
> 
> * If this flip is not good enough, there is a chance that your flip will be reported and you will lose your validation rewards.
> * The cost of deleting filp is aproximatly ____ DNA.
> 
> Can flip deletion fee be calculated aproximatly and placed up there?
> I guess this way we can raise awareness about needed flip quality.


Plain and simple:

"If you make BAD flip, you will lose all DNA rewards!"
"The cost of deleting a flip is ~8dna"

When they see the message, it will make them think twice about submitting. And also, they will ask in the @Idena channel about this, and they'll get info about making good flips!

**Comment by redDwarf03** [comment]
suggestion added in my Idena mobile app

**Comment by aidenaio** [comment]
we work towards this 
bad flip explainer is done in #593
