### ISSUE TITLE
Suggestion: Information banner for Newbies, stake+locked lost if they miss validation

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-desktop#398]
Hi,
Well the title said it all, if we can have some banner for Newbies that will give them information that the stake+locked coins will be lost if they miss next validations.
Maybe best if it said "**You will lose 45 DNA if you miss next validation.**" to raise awareness.

![image](https://user-images.githubusercontent.com/37978870/89636225-92f73000-d8a8-11ea-91d4-483478ac2d53.png)

**Comment by aidenaio** [comment]
we move in this direction
closing
