### ISSUE TITLE
Suggestion : An option to clear the archived flips 

### ISSUE THREAD

**Issue by RealMahmoud** [idena-network/idena-desktop#405]
Hello again 😅 , it would be good if there is a small button under the view flip button to delete the flip from the flips.json file 😃 ..
Also maybe a button to clear all the old/archived flips
![image](https://user-images.githubusercontent.com/61373609/90287759-c7ef1e00-de78-11ea-9291-32762d3a2949.png)

**Comment by rioda-org** [comment]
Yes, after some time of running client, json gets big and flip making gets laggy.

**Comment by aidenaio** [comment]
noted

**Comment by aidenaio** [comment]
btw we already have some https://github.com/idena-network/idena-desktop/blob/8d6fa05171406e3a447dfcd2e47eb583becf1159/renderer/pages/settings/index.js#L61

**Comment by aidenaio** [comment]
done in #481.

the rest is available in `DEV` mode
