### ISSUE TITLE
BUG while publishing flip 

### ISSUE THREAD

**Issue by RealMahmoud** [idena-network/idena-desktop#406]
hello again 😆 : after i clicked the submit button i clicked on My Idena button so the client navigated there and i went back to the Flips section and i found the the flip got submitted but not saved/recorded as a flip in the client and that's because the client didn't wait for the Tx ...So please fix that 😀 
![image](https://user-images.githubusercontent.com/61373609/90289324-edc9f200-de7b-11ea-9fc2-50bd7adb6a05.png)

**Comment by aidenaio** [comment]
added to the backlog
