### ISSUE TITLE
Suggestion: Make right click menu with "Paste" option on input fields

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-desktop#407]
Suggestion: Make right click menu with "Paste" option on input fields.

We have lots of people who are typing in invitation code by hand because the "can't paste" it.

**Comment by busimus** [comment]
There's already a Paste button next to the the invite field, and Ctrl+V works too.

![paste](https://user-images.githubusercontent.com/4591884/90332056-e4f43000-dfe3-11ea-86a2-6c59d2956072.png)

**Comment by rioda-org** [comment]
Well that takes care of that, did not know that...
