### ISSUE TITLE
Local DNS resolution does not work

### ISSUE THREAD

**Issue by Swader** [idena-network/idena-desktop#411]
The app does not respect local DNS resolution as specified in `/etc/hosts`.

- OS: Windows 10 (app), Ubuntu 20.04 (node)
- Client version: 0.15.5
- Node version: 0.21.5

Steps to reproduce:

1. Run a node on a remote server or VM on the same network
2. Give this server a name in `etc/hosts`, e.g. `192.168.0.5 foobar`
3. Connect via the app using the Remote Node function, and enter `http://foobar:9009`
4. Notice that the app will fail to connect with `http://foobar:9009` but will work fine with `http://192.168.0.5:9009`

Solution: make app respect `hosts` definitions.

**Comment by midenaio** [comment]
@Swader please try to add the following section into the node's config file:

```
"RPC": {
  "HTTPVirtualHosts": ["*"]
}
```

**Comment by Swader** [comment]
If you mean `settings.json`, I tried it but it didn't work, same thing. How should my `settings.json` file look after this? Perhaps I did something wrong. And do you mean node or app?

**Comment by midenaio** [comment]
It's a node config file. Read more for running Idena node with a custom config file: https://github.com/idena-network/idena-go#running-idena-go

**Comment by Swader** [comment]
That worked, thank you!
