### ISSUE TITLE
flip_longHashes timeout during long session

### ISSUE THREAD

**Issue by hlbcal** [idena-network/idena-desktop#415]
Hi Dev,

I encountered "flip_longHashes" timeout during long session yesterday. After a successful short session, there is no flip show up at all during that long session, It displayed as "1 out of 0" on my GUI. 

I checked the log file, "flip_longHashes" was only called twice and both were timeout. My short answer was submitted successfully according to my log file. 

Wondering if you can add a "Reload" button so we can re-initiate this "flip_longHashes" API call upon error during validation.

![IDENA_LongSession_NoImages](https://user-images.githubusercontent.com/34809039/91649444-e2dfa600-eaa6-11ea-8388-b440a16191d7.png)

I tried re-launch desktop client several times, but that does not help.

Below zip is the log file from my external node.
[output.zip](https://github.com/idena-network/idena-desktop/files/5146635/output.zip)

**Comment by midenaio** [comment]
@hlbcal could you attach the Idena app log file: `%appdata%/idena/logs/idena.log`

**Comment by hlbcal** [comment]
[idena.zip](https://github.com/idena-network/idena-desktop/files/5150422/idena.zip)

Hi Midenaio, pls see this attached.

**Comment by RealMahmoud** [comment]
same bug happened to 2  of my friends but during Short session ..
