### ISSUE TITLE
Keep UI composition when robohash is not working

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-desktop#416]
Today we had many cases where robohash had issues to provide robot images that are used.
In some cases it's not that important, but in others like, transactions screen, it gets imposible to see anything.

![image](https://user-images.githubusercontent.com/37978870/92038738-21f64b80-ed74-11ea-9e2b-80c06884a8ca.png)

Maybe to introduce some dummy img if robohash does not provide image, to keep UI in its place.

**Comment by RealMahmoud** [comment]
@rioda-org i think this can be closed now after https://github.com/idena-network/idena-desktop/pull/465 got merged
