### ISSUE TITLE
invite problem

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-desktop#427]
What happened: I had 2 invites. Wanted to invite someone - pressed enter too fast (before hitting advanced and entering the address of the user). Deleted invitation (in the hope I will have 2 again afterwards) and then tried to invite again and got "not enough invites left"

my address: 0x75e460f68a5d423cd6eaf768f8f687ec1985ad76

**Comment by midenaio** [comment]
Please try the following:
1. Edit the `invites.json` file at located at `%AppData%/Idena/`
2. Remove the `"deteledAt": ...` line and the comma symbol at the previous line for the deleted invitation
3. Restart the app

**Comment by ligi** [comment]
Then I see the one invite I deleted - but somehow the second is still missing.

**Comment by midenaio** [comment]
@ligi Could you send the `invites.json` file at info@idena.io
