### ISSUE TITLE
[BUG] [Validation] No flip for short session

### ISSUE THREAD

**Issue by xavierh81** [idena-network/idena-desktop#433]
Hi ! 
I'm on the Idena network since 5-6 months and I got suspended 2 times due to an issue with the Client (or at least.. I think).

The same problem occurred 2 times, one during August validation and one yesterday.

None flips were loaded during the short session so after the 2min countdown, I just got the famous "Validation failed" message. It's really frustrating.. and very penalising  :/

My node is hosted on a dedicated server at Scaleway hosting (https://www.scaleway.com/fr/dedibox/start/start-2-s-ssd/). Maybe this server is not enough to handle the Idena validation sometimes? I don't know..

Apparently, I was not alone to not get any flip in the short session (cf discord messages).

I attach the logs of the client right below:
[log.txt](https://github.com/idena-network/idena-desktop/files/5216892/log.txt)

And the node logs here: 
[node.13_09_2020.log](https://github.com/idena-network/idena-desktop/files/5217050/node.13_09_2020.log)

Have you any idea?

**Comment by aidenaio** [comment]
Thanks for the report. We're investigating the case.

**Comment by aidenaio** [comment]
Closing, plz update the node.
