### ISSUE TITLE
[BUG] Cannot click any of the side buttons on Linux

### ISSUE THREAD

**Issue by eggmund** [idena-network/idena-desktop#438]
Hi,
I have run into an issue where I cannot click any of the side buttons (My Idena, Wallets, etc). They react when I mouse over them, however when I click nothing happens (client version 0.16.1). I can click the buttons on the "My Idena" tab though (Invite, New flip, etc).
I am using dwm as my window manager, however I have also tried this on XFCE and had the exact same issue.

I have attached the logs, however I also got this message when running `idena-desktop` in the terminal:
`Error occurred in handler for 'CHECK_DNA_LINK': No handler registered for 'CHECK_DNA_LINK'`

[idena.log](https://github.com/idena-network/idena-desktop/files/5232164/idena.log)

**Comment by busimus** [comment]
I always got that error message on Linux, though I've never had the issue you describe.
Have you tried starting the client from source [as described in the README](https://github.com/idena-network/idena-desktop#development)?

**Comment by eggmund** [comment]
Hi, thanks for the quick response :)
I just started the client from source and the issue seems to be fixed... However they were unresponsive for a while after opening the program, as it was still compiling each of the pages.
I think it may just be an issue with the package in the arch user repository that I was using (`idena-desktop-git`). It compiles the code from the github however it still has this issue, which I think is down to those pages not being compiled when the program is installed by the package.
Building
