### ISSUE TITLE
Active flip details won't be shown at "View flip" after replacing previous one

### ISSUE THREAD

**Issue by sekisanchi** [idena-network/idena-desktop#455]
Here's what I observed on my stable environment with Client 0.17.1/Node 0.22.1 on macOS Catalina 10.15.7 within    
Epoch#56 

1. Submit 3 flips and confirmed them at "created flips" tab at scan.idena.io/identity/0x........ showing hash/date/size of each
2. Delete a flip with Idena app 
3. Submit a new flip with different words, and then confirm the new creation date of it at scan.idena.io/identity/0x....
4. At Idena app/Flips/MyFlips panel, "View flip" for the new addition shows blank with the title ("View flip") only while other two shows the two words and images for the flip correctly

**Comment by aidenaio** [comment]
Thanks for reporting this 🤝.
We'll look into it.

**Comment by sekisanchi** [comment]
The node concerned is in "Newbie" status

**Comment by aidenaio** [comment]
i cannot reproduce this.

closing, pls submit a new one if it's still an issue
