### ISSUE TITLE
suggestion for "submit answer" button and tutorial validation windows

### ISSUE THREAD

**Issue by emporytechnology** [idena-network/idena-desktop#460]
hello dev, I would  like to proposed the feature change regarding "submit answer" button

full story can be found here
[https://discuss.idena.website/d/21-i-failed-the-validation-because-of-a-button-heres-my-story-and-suggestion](https://discuss.idena.website/d/21-i-failed-the-validation-because-of-a-button-heres-my-story-and-suggestion)

Suggestion for "Submit Answer" Button

I propose changes as follow
1. Make a confirmation before submitting the flips
Confirmation like "You sure with your answer ?" will make a different whether get your identity killed or validated  

2. Un-active the "Submit Answer" button before all flip answered or viewed
Making "Submit Answer" un-active (unclickable) by greyed it out, and when user viewed all the flip or answered it then make it active (clickable). This way will reduce the chance user clicked "submit answer" button very first time they see it (like I did).

3. Make a guidance about how to do validation before validation start (10 minute before start)
As we know the validation windows was quite confusing (misleading answer button, non logical order, tiny next arrow). So to makes thing easier for the newcomers, and makes it remember to existed user, I proposed guidance windows on how to do validation 10 minutes before validation start. This way newcomers will benefit to what to expect on validation, how to do validation, get confidence to their very first validation . The existed user will benefit to remember how to do validation (because validation 2 weeks apart), and reduces the chances of confusion. 

**Background story**
"Submit answer" Button Problem

Ok, we start with the validation windows
[URL=https://i.imgur.com/hImsmTg.png][IMG]https://i.imgur.com/hImsmTgh.png[/IMG][/URL]
[image courtesy of [https://bruno.id/running-a-dedicated-idena-node/](url)]

You get flips on the center, arrow left and right beside flips, the flip counter below flip, and "submit answer" button with blue button on the left button corner. 

I'll ask you question, when you do flip with limited amount of time, answer it and see the blue submit answer button more prominent than arrow left / right, what will you choose ?

click the "submit answer" button right. Because your intuition will go to below and the blue submit button more prominent than arrow left / right so it's logical to click it because of the logical flow.

You see, the problem is when you click the blue more prominent "submit answer" button, there are **NO CONFIRMATION TO ENDED THE SHORT SESSION AT ALL**! it just... end.... and start the long session

There's no "You sure with your answer" type of confirmation, like I said it just end...

WHY IT MATTER ?
it's so stupid  to got killed even tho you attend the validation, you submit short and long session answer, with 100% accuracy and getting killed because of the submit button.

**Comment by emporytechnology** [comment]
that's weird because my issue #460 exactly opposite at this when my submit answer button active on the first flips at short session and I clicked it.

**Comment by emporytechnology** [comment]
UPDATE #1
Digging deeper I found idena validation tutorial on medium

https://medium.com/idena/how-to-pass-a-validation-session-in-idena-1724a0203e81

and found validation windows there

so by default, submit button unactive when you didn't choose the answer and became active when the answer selected.

When you have solved the flips, the Submit answers button will become active — submit your answers then. Otherwise they will be submitted automatically when the short session time is over.

what baffled me is the wording telling to answer and click on the submit button after answered the flips, EXACTLY WHAT I DID WRONG!

The solution to the problem is EXTREMELY SIMPLE, just don't active the button until user at least view all the flips, or user answared all the flips.

Current implementation when user click the answer and submit button activated thinking logically user should click the button when the reality user should click the TINY, GREY arrows.

**Comment by midenaio** [comment]
Thank you for reporting it. We’ll improve the flow to prevent accidental short answers submission until all flips are answered.

**Comment by aidenaio** [comment]
#467

onboarding part is in progress as well #523
