### ISSUE TITLE
Short validation result can be submitted without having the last flip selection - possible UX/Operational design issue    

### ISSUE THREAD

**Issue by sekisanchi** [idena-network/idena-desktop#461]
**Describe the issue**
At Identity validation for epoch 56, I believed I answered all the flips in the short session, but the scanner says that I missed the last, 6th flip. Not sure if this was human error upon psychological pressure, or by other reason. 
Since the "Submit.." button is activated at the last flip, I assume it is intended to submit after selecting all the 6 flips, or not able to submit. 
Also I remember the first time experience on short session, which I did zoom into flip image, and missed finding the count down timer located out below the screen.

Considering above two experiences, short validation panels should have  

a. Countdown timer/submit button at the top, or below the title of the panels     
b. Having remaining or selected flip count like "3/6" near the timer. 
c. Auto submission at the timer expiration, if the user attended. (some bot protection?)         
     

**Steps to reproduce**

Not sure 

**Idena Client logs**
**Idena Node logs**

Could you set some safety protection up, like https://github.com/StackExchange/blackbox?

**Screenshots / Screencasts**
![Identity_validation_0xfc212d6963081a0cc04a4486165771c3a5e46c9c_for_epoch__0056_-_Idena_Blockchain_Explorer](https://user-images.githubusercontent.com/1669550/96022154-64d73300-0e8b-11eb-9557-93c6f13351cf.jpg)

**Environment:**
 - macOS catalina 10.15.7
 - Node mode: remote 1GB memory machine, not sure memory swap was enabled there or not, stopped working during the long session and restarted. 
 - Client version 0.17.1
 - Node version  0.22.1 

**Additional context**
Did not find any other case by looking around manually, but  scanning might be some by scanning records. 
Any handy tool like dune for Ethereum?

**Comment by sekisanchi** [comment]
I was holding it for hours to see the items specified in the newly added issue templates, and please assume it's written before #460.

**Comment by emporytechnology** [comment]
"Since the "Submit.." button is activated at the last flip"

that's weird because my issue #460 exactly opposite at this when my submit answer button active on the first flips at short session and I clicked it.

I agree on suggestion oh here

**Comment by sekisanchi** [comment]
I was running nodes with small 1GB RAM at that moment, and there might be several race condition among the node and chain. Since I did not know about event logs and several updates since then, I'd like re-examine the detailed UX validation later with detailed interaction among chain, node and front.
