### ISSUE TITLE
Check if the user already submitted short after client restart

### ISSUE THREAD

**Issue by RealMahmoud** [idena-network/idena-desktop#463]
One of friends mistakenly exited putty after submitting short session .. So he connected again to the vps using putty but he found that the flips shows that there is no data available So he exited the client and opened it again and then he found that the validation is not showing up ..
So there is 2 issues here 
1- The client doesn't Auto check again downloading the flips from the node after fail download
2- The client doesn't start long session again although the short session got submitted 

Possible Fixes :
1- Redownload button on each flip
2- Auto start long if the user submitted the short session

**Comment by aidenaio** [comment]
validation session is persisted. validation is not popping up is another case.

closing now.
