### ISSUE TITLE
wording in message: to get maximum rewards use all reports 

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-desktop#469]
There is a new message at the end of the long session:

![Selection_283](https://user-images.githubusercontent.com/111600/99186560-611c2200-2751-11eb-999a-a1d4948a5dee.png)

I think the wording here should be changed. If you have good flips in the long session (the best one so far) - why should you do more reports?

In the discord chat I saw I am not the only one irritated by this message. Also people ask for a back button there.

**Comment by aidenaio** [comment]
_Cancel_ done in https://github.com/idena-network/idena-desktop/pull/473
