### ISSUE TITLE
oracles: prevent NaN years

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-desktop#475]
**To Reproduce**
1. Go to 'oracle voting'
2. Click on 'new voting'
3. enter 4200000000000 number in Blocks

![Selection_304](https://user-images.githubusercontent.com/111600/100484534-1f01c180-30fd-11eb-905f-b5f37dc7d54d.png)

Fun fact - you see a year in the voting then - there it is not NaN

![Selection_305](https://user-images.githubusercontent.com/111600/100484594-5a9c8b80-30fd-11eb-88b5-5f61bfce70db.png)

**Expected behavior**
It should reject numbers over a certain value

**Environment:**
 - OS: Linux
 - Node mode: remote - 0.0.1
 - Client version0.19.0-rc4

**Comment by ligi** [comment]
should also prevent negaive numbers here (and maybe also 0)

![Selection_306](https://user-images.githubusercontent.com/111600/100484743-e6aeb300-30fd-11eb-812e-3e4f60763cdb.png)

**Comment by aidenaio** [comment]
done
