### ISSUE TITLE
[Validation issue] Idena not loading first verifications

### ISSUE THREAD

**Issue by GamerD4rker** [idena-network/idena-desktop#476]
**Describe the issue**
Idena didn't loaded the 1 minute verification.

**Steps to reproduce**
I waited for the validation then I pressed validate
After that I tried to see if the validation was gonna load the stories
But it didnt and it gave error in the developer options console: Uncaught (in promise) Error: Error invoking remote method 'CHECK_DNA_LINK': No handler registered for 'CHECK_DNA_LINK'
    at EventEmitter../lib/renderer/api/ipc-renderer.ts.ipcRenderer.invoke (ipc-renderer.ts:28)

**Idena Client logs**
ipc-renderer.ts:28 Uncaught (in promise) Error: Error invoking remote method 'CHECK_DNA_LINK': No handler registered for 'CHECK_DNA_LINK'
    at EventEmitter../lib/renderer/api/ipc-renderer.ts.ipcRenderer.invoke (ipc-renderer.ts:28)
DevTools failed to parse SourceMap: file:///C:/uri.all.js.map

**Idena Node logs**
No problems

**Validation context**
There was nothing in the stories because it didn't loaded.

**Screenshots / Screencasts**
![Screenshot_1](https://user-images.githubusercontent.com/75317531/100748370-282fae80-33db-11eb-96ca-3804b7282e7b.png)
![Screenshot_2](https://user-images.githubusercontent.com/75317531/100748459-3ed60580-33db-11eb-8cc7-4a03ca369b8e.png)

**Environment:**
 - OS: Windows
 - Node mode: remote (VPS)
 - Client version 0.18.0
 - Node version - 0.23.2

**Additional context**
My node address is: 0x8f089b03a7037313fd4d81b03ab48c9f6d14bdf3
I hope I can repeat the validation since it glitched

**Comment by aidenaio** [comment]
closing
