### ISSUE TITLE
oracles: Bitcoin address is elipsized in question

### ISSUE THREAD

**Issue by biafra23** [idena-network/idena-desktop#477]
**Describe the bug**
The Bitcoin address `bc1qgdjqv0av3q56jvd82tkdjpy7gdp9ut8tlqmgrpmv24sq90ecnvqqjwvw97` is shortened to `bc1qgdjqv0av3q56jvd82tkdjpy7gdp9ut8tlqmgrpmv24sq90ecnvqqjw...` in the Oracle question. When I copy the whole question, the correct address is copied. This seems to be a displaying problem. 

BTW: The title is also shortened to: 
> Did a 60,000 Bitcoin-Transaktion specified... 

The full title is: 

> Did a 60,000 Bitcoin-Transaktion specified in description happen or not?

**Module**
- Oracle

**To Reproduce**
1. Go to 'Oracle voting'
2. Click on 'To do'
3. Select voting with id 0xd88bdd5955afaa9a272d3e5968beddaf3a0aeafa

**Expected behavior**
The Bitcoin address should be shown completely

**Identity context**
n/a

**Idena Client logs**
n/a

**Screenshots / Screencasts**
![image](https://user-images.githubusercontent.com/246473/100858123-db58e000-348d-11eb-85b8-31fdfa46f9ed.png)

**Environment:**
 - OS:  macOS 10.15.6 (19G73)
 - Node mode: remote
 - Client version: 0.19.0-rc.4
 - Node version: 0.0.1

**Additional context**
Resizing the window does not prevent elipsization

**Comment by aidenaio** [comment]
this is done in somewhat NY-ish release 😀
