### ISSUE TITLE
Let clients ping each other offchain and use result onchain

### ISSUE THREAD

**Issue by ubiubi18** [idena-network/idena-desktop#484]
I have a proposal, that i hope could probably help to handle three major problems of idena network better: 1. the problem of slow vps, 2. the problem of governance and oracle voting beeing at constant risk due to strong growing human farms, 3. the problem of constant wealth transfer into farmers regions, who need to sell idna regularly to pay their expenses and make idena thereby cryptonomicly less attractive to the rest of the world.

Proposal: 1. Let the user self assign onchain to global regions. 2. Let the clients behind connected nodes ping each other off chain in short session and let them publish the results onchain in longsession. 3. Use ping and global regions to weight rewards, votes, maybe even mining distribution against each other

Argument:
While there are undoubtedly nearly unlimited possibilities for Clients from your direct neighborhood to get a low ping on each other, there is only a limited possibility for example for a client from the other side of the globe to get a faster ping on a Client in your neighborhoods than another client in your neighborhoods can achieve ideally. 

You could introduce lower rewards for lower Pings. Then you organize and weight nodes connections at the same time in relation to global region and ping speed, so that they allways prefer connection to nodes in self assigned regions which hold higher chances of higher ping speed. 

Result: That will incentify users to: 1. Use faster vps or where possible run idena node at own pc at home duiring session, not to risk to loose ping speed. That probably helps to takle the problem of weak vps for the network. 2. User might self-assign honestly to real global region of their client, so that the possibility for fast ping is higher and the risk for lower rewards due to low ping is lower. 
3. That onchain-knowledge can be used for a lot of things, while not compromising participants anonymity. For example: Since human farms likely can recruit their workers only in low salary countries, it might turn out that idena participants are concentrated in certain global regions. For governance as well as for oracles you could use the knowledge to assign only a limited weight of votes (or even mining rewards) to certain global regions. As long as there are no AI-farms, farmers would physically not be able to circumvent that limit, they can't bring their workers into other regions of the globe. So risk for governance and oracles functionality ( maybe as well as selling pressure )  could be contained better. 

Discussion: Do you think that idea is worth exploring? For sure it can also have its downsides, like shared nodes having too high traffic due to clients pings, and like making successful equipment and vps more expensive and thereby excluding poorer people. Also it is a political question, if wealth transfer from rich countrys to (farm workers) poor countrys is something bad or something good. 

My personal opinion is that voting and governance could profit and need to be defended at all costs!

Thx anyway for your brilliant work 👏

**Comment by ubiubi18** [comment]
Another interesting side effect opportunity: you could limit the number of possible participants each region as well es distribute a fixed percentage of global mining rewards go to certain region, which is only shared between all miners regionally. Human farmers - who have most workers in one global region - will have a limited possibility to profit and therefor have a much higher incentive to do marketing in other regions of the globe than in their own region. They would need to help idena to globalize, if they want to stay profitable.

**Comment by jugi1** [comment]
Maybe in theory this is possible but I am not sure this can work in real life.

**Comment by aidenaio** [comment]
hey @ubiubi18 

thanks for your kind words. this is the whole point of how `idena-node` works 🙂
