### ISSUE TITLE
Community translation at Flips tab does not work with "ja"

### ISSUE THREAD

**Issue by sekisanchi** [idena-network/idena-desktop#490]
**Describe the bug**
Community translation section at Flips tab does not work returning an error message  " invalid value 'language' "  
The error does not occur with 'fr'
![Fullscreen_2020_12_25_8_25](https://user-images.githubusercontent.com/1669550/103111005-7eff6f80-468b-11eb-9026-ac4876dce273.jpg)

**Module**
- Flips
**To Reproduce**
1. Go "setting" tab and change the language into "ja"  
2. Type appropriate translation
3. Click on "submit"

**Expected behavior**
No error message with proper text inputs

**Identity context**
Not applicable

**Idena Client logs**
Not available

**Screenshots / Screencasts**
see above

**Environment:**
MacOS 10.15.7
 - Node mode: both  built-in and remote (VPS)
 - Client version [e.g. 0.19.1]
 - Node version [e.g. 0.24.0]

**Additional context**
None

**Comment by mbidenaio** [comment]
Fixed. Please try again.

**Comment by sekisanchi** [comment]
Verified the fix. Thank you! 

![shot](https://user-images.githubusercontent.com/1669550/107160633-c727e680-69da-11eb-8828-087b47462b2e.jpg)
