### ISSUE TITLE
oracles: "The voting must be prolonged"

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-desktop#504]
got this error message:
![Idena_363](https://user-images.githubusercontent.com/111600/103480800-baf6ab00-4dd6-11eb-8eb5-b57d74b9205d.png)

I think it should state by whom it must be prolonged (I *guess* it is an action that must be done by the initiator of this oracle. 
Maybe even this should not be offered to vote in To Do after all

**Comment by aidenaio** [comment]
done in #505
