### ISSUE TITLE
idena-desktop version is 0.0.1

### ISSUE THREAD

**Issue by kimxilxyong** [idena-network/idena-desktop#511]
**Describe the bug**
The version in package.json is not pumped by the releaser. When i do compile myself i always get 0.0.1
It would be nice if the person doing the releases update the version and push it back into git.

**Module**
Building process

**To Reproduce**
git clone https://github.com/idena-network/idena-desktop.git
npm init
npm run build
npx electron-builder --linux tar.xz

**Expected behavior**
dist/idena-client-linux-0.19.4.tar.xz
but got
dist/idena-client-linux-0.0.1.tar.xz

**Environment:**
 - OS: Manjaro Linux 20.2.1
 - idena-desktop 0.19.4

**Additional context**
Maybe i don't understand the building/release procedure

**Comment by aidenaio** [comment]
this is intentionally and done within the ci/cd pipeline https://github.com/idena-network/idena-desktop/blob/d12f20c9744d847754e5b6c1318b7761c2c3e2c1/.github/workflows/release.yml#L43
