### ISSUE TITLE
Very low-res images when using add via google

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-desktop#512]
**Describe the bug**

When adding images via "Search on google" the images are very pixely (low res)

**Module**
Pick one of:
- Flips (flip creation)

**To Reproduce**
1. Go to Flips
2. Click on "next step"
3. Click search on google
4. Enter term
5. Select image

**Expected behavior**
Should be higher res

**Identity context**
- Identity status
- Identity address 
- Link to the Explorer page with the current validation

**Environment:**
 - OS: Linux
 - Node mode:remote
 - Client version 0.19.2
 - Node version 0.24.0

**Comment by aidenaio** [comment]
yes, because of the thumbnails we use not actually images. we're limited by the size of the flip
