### ISSUE TITLE
Short Session Bug on The Idena Node App

### ISSUE THREAD

**Issue by Panto9** [idena-network/idena-desktop#526]
I participated in the validation ceremony today, 5th Feb 2021. I finished on time, with at least 13 - 15 minutes left. After the end of the validation, I see that Idena says I submitted my short session flips late. I'm like what the heck!
I submitted my short session with at least 30 seconds to spare, even though three of the 6 flips failed to load, but I did submit on time. So why on earth, and how did it register that I submitted late? I checked the explorer and lo and behold, it says 5/2/2021 14:36:36 short answer proof for which I don't know what that means, but I do know it is unlikely to be when I submitted. Please can the be looked into, now my status says wait for confirmation when I was sure I was going to be upgraded to human today.

**Comment by Panto9** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/75354970/107048742-92911080-67c9-11eb-861b-17ab2aca8316.png)
![Screenshot (15)](https://user-images.githubusercontent.com/75354970/107048749-93c23d80-67c9-11eb-983f-73b29dde0bcf.png)

**Comment by Panto9** [comment]
https://scan.idena.io/address/0x10c1ffeb94a52b74abf4115f5a8526b8591ce853

**Comment by aidenaio** [comment]
hey

this is more like node/network-related issues. dozen of improvements have been done here

closing
