### ISSUE TITLE
Improve bad error message when mac-os is too old

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-desktop#548]
this is the desktop part of this issue:

https://github.com/idena-network/idena-go/issues/646

on mac you only see this:

![Selection_015](https://user-images.githubusercontent.com/111600/110649440-e2446c80-81b9-11eb-9c2b-689f8b1e88f5.png)

It should do a version check and provide a helpful error message in case the machine is too old

**Comment by aidenaio** [comment]
#623
