### ISSUE TITLE
Install folder for ElectronJS

### ISSUE THREAD

**Issue by sergeybrava** [idena-network/idena-desktop#568]
Plz fix some stuff!  I can be wrong but I can’t change “install folder”. Installer put all files directly on my main disk. Electron framework have tools for this.

**Comment by aidenaio** [comment]
hey

yeah it's possible but probably not the thing you're actually looking for.

some files: logs, configs, built-in node assets, will still be written on the allowed (for the user) locations depending on the environment variables.

allowing to change install folder is not the priority rn. the rest can be done through the setting your envs up.
