### ISSUE TITLE
Submitting incomplete verification

### ISSUE THREAD

**Issue by QuickMythril** [idena-network/idena-desktop#569]
**Describe the issue**
When doing verification, there is nothing to help prevent users from accidentally submitting their answers before they are complete.  I think the Submit button should not even be available until you have answered all flips, but if there is a reason to allow people to do so, then at least a warning message should ask to confirm that is what you want to do.

As this was my first verification, i was focused on the images and the timer.  The SUBMIT button was very prominent in the corner and i just reflexively pressed it, thinking it was to submit my first answer and move to the next.  I realized right away i should have pressed the arrow, but they are very tiny, and they don't really catch your attention.  It was too late, there was no cancelling, no going back to change my answers though i still had time left on the timer.

**Steps to reproduce**
Start validation, answer one flip, press Submit, fail validation.  >_<

**Validation context**
- Candidate > Not Verified
- 0x6118b2fcb8075a54b3ef3f02c4d7aa5a5c513afb
- https://scan.idena.io/identity/0x6118b2fcb8075a54b3ef3f02c4d7aa5a5c513afb/epoch/67/validation

**Environment:**
 - OS: Windows 10 (Build 21327.rs_prerelease.210226-1427)
 - Node mode: built-in
 - Client version 0.22.2
 - Node version 0.25.2

**Comment by aidenaio** [comment]
#621
