### ISSUE TITLE
You can lose your stake, all your mining and validation rewards if you delegate your mining status.

### ISSUE THREAD

**Issue by idena-Egyptian-Pharoh** [idena-network/idena-desktop#571]
https://github.com/idena-network/idena-desktop/blob/261481bb4829a14927e5d4c527910e5ed347188f/locales/en/translation.json#L596

edit it to : You can lose your stake, all your mining and validation rewards if you delegate your mining status to unknown address

**Comment by Toni-d-e-v** [comment]
done

**Comment by aidenaio** [comment]
please PR 🤓
