### ISSUE TITLE
Looping short sesh

### ISSUE THREAD

**Issue by Toni-d-e-v** [idena-network/idena-desktop#576]
**Describe the issue**
So when you validate client will go to my idea and loop back to the short shesh in infity loop
**Steps to reproduce**
1. Wait for the validation end
2. wait few minutes
3. again click back to my idea

**Screenshots / Screencasts**
https://media.discordapp.net/attachments/838682151510999080/839857660504571914/unknown.png?width=633&height=454

**Environment:**
 - OS:Linux 0.19.4 including version
 - Node mode: remote (VPS)

 - Node version 0.25.3

**Comment by aidenaio** [comment]
hey @Toni-d-e-v do you use the latest version of the desktop client?
seems i cannot reproduce this

**Comment by aidenaio** [comment]
i cannot reproduce this

we've got a message showing that the user is late with the submission, and then it goes to My Idena straight. this is by design
