### ISSUE TITLE
stuck bug

### ISSUE THREAD

**Issue by bulusite** [idena-network/idena-desktop#603]
**Describe the bug**
When i open the idena client,then my mbp is very stuck,i think it use too much cpu.

**Module**
Pick one of:
- Profile
- Flips
- Wallets
- Contacts
- i18n
- Settings

**To Reproduce**

**Expected behavior**

**Identity context**
- Identity status
- Identity address  0x061a7bf0030c9636bf960faec6e5cbcbae8aa60b
- **Describe the bug**

**Module**
Pick one of:
- Profile
- Flips
- Wallets
- Contacts
- i18n
- Settings

**To Reproduce**

**Expected behavior**

**Identity context**
- Identity status
- Identity address 
- 
- Link to the Explorer page with the current validation

**Idena Client logs**
If possible, add [client logs](https://idena.io/?view=guide#guide-issues-4) to help us investigate your problem.

**Screenshots / Screencasts**

**Environment:**
 - OS: macOS 10.15.7
 - Node mode: built-in or remote (VPS)
 - Client version 0.26.1
 - Node version 0.24.1

**Additional context**

- Link to the Explorer page with the current validation

**Idena Client logs**
If possible, add [client logs](https://idena.io/?view=guide#guide-issues-4) to help us investigate your problem.

**Screenshots / Screencasts**

**Environment:**
 - OS: macOS 10.15.7
 - Node mode: built-in or remote (VPS)
 - Client version 0.26.1
 - Node version 0.24.1

**Additional context**

**Comment by aidenaio** [comment]
hey @bulusite 

do you use built-in or remote node? also could you plz elaborate more: what's your cpu metrics, do you use build or dev mode, etc
