### ISSUE TITLE
My Current Task Click-Focus

### ISSUE THREAD

**Issue by hngts** [idena-network/idena-desktop#605]
**Bug Description**
When I click on My Current Task portion above Next Validation: (date) on the left sidebar, blue bordered line is being drawn (just like when html input element is focused for instance) around whole portion and the application does switch to Flips, which is expected, however, that focus on the left sidebar still remains. And when I click on it again, or when I click on My Idena tab instead, I got a blue tip at the bottom left screen on how to get invitation via Telegram group. The thing is that I have Human status. 

1. Click on My Current Task
2. Click on My Idena  or My Current Task - again.

**Expected behavior**
I would expect that no tip of this kind is shown to already invited/activated identities, nor there should be focus style applied to My Current Task link/portion. In fact, nothing should happen when I click on My Current Task - again. This is very annoying bug. 

 - OS: Debian Buster stable 
 - Node mode: remote (LAN)
 - Client version [e.g. 0.24.2]
 - Node version [e.g. 0.26.2]

**First Click on My Current Task**
![crop1](https://user-images.githubusercontent.com/20982627/120067175-88499980-c07a-11eb-9ec3-fb843d28c3db.png)

**Second Click on My Current Task or on My Idena Tab**
![crop2](https://user-images.githubusercontent.com/20982627/120069135-9d2b2a80-c084-11eb-884a-e8abb2bf15e5.png)

**Comment by aidenaio** [comment]
hey @hngts 

thanks for reporting this?

do you use the same app for different identities?

**Comment by hngts** [comment]
@aidenaio 

No, I use only one identity, no delegation and similar. Havent tried with other identities, though. Currently all (both client and node) updated to the latest versions, and client is connected to the separated, remote node (local area network PC in my case), if that matters.

**Comment by hngts** [comment]
Still no progress with this kind of issue .. ?

**Comment by aidenaio** [comment]
hey 👋 
a lot of work had been done here #625 
here is the fix for the case above 6bf83dd285fd5268b3b2428841994f07356660be

**Comment by hngts** [comment]
Awesome. :) Thnx. Now, we just need to fix the price with the super-glue... :/ Just saying, not complaining.
