### ISSUE TITLE
Do not suggest "Activate mining status" when it is activated

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-desktop#676]
Currently it suggests me "Activate mining status" as the current task even I did this task already.

![idena_bug](https://user-images.githubusercontent.com/111600/132266650-b6c65d46-5e12-4f61-bc7c-8d74ed204baf.png)

**Comment by aidenaio** [comment]
you're _delegating_ sir while it's only _mining_ expected here

we'll sort it out
