### ISSUE TITLE
Notify user of a lost connection during session

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-desktop#686]
I've tried to help out one member to troubleshoot validation for his friend who had Late submision as a result of short session.

PC hardware was fine:
Laptop i3-3227U, 8GB ram, Windows 8.1
Logs: [Marcos_friend.zip](https://github.com/idena-network/idena-desktop/files/7159811/Marcos_friend.zip)

He was using Desktop App with built-in node. Connection he used was mobile 3G network. The problem is, he passed first validation using this same setup, and now he can not accept that his connection was problem this time around.
Everyone should be aware that mobile internet or Wi-fi could work fine, but it's a lottery, connection depends on how the wind blows during short session. So it is not recomended to run node on it. Web App is the way.

Node log shows that all his peers disconected during short session.

```shell
INFO [09-01|13:30:37.605] Start loop                               round=3322964 head=0x9d0c778e76a53e67422152670dfdf8f786f29b16fae442d71ca53fe0bc40a279 peers=8   online-nodes=2604 network=8402
INFO [09-01|13:30:40.901] Peer disconnected                        id=Qmf2GsTHGvGRoYRGgMXA37GBGwf5PyMC6YtD842KuV5VBn
INFO [09-01|13:30:41.952] Peer disconnected                        id=QmShA7NuHNBiFgkRwmxEw7GFzf2FaekNY8e5RZTLuULAfe
INFO [09-01|13:30:42.296] Peer disconnected                        id=QmW39tEimHvZKPrZgaKieF9wU9Dqzv1f62Z516BSjm1d8u
INFO [09-01|13:30:43.133] Peer disconnected                        id=QmUiF2bWV2e3oE3rrA2oSZsfiDX737yMCP5jHUW5ohqjoE
INFO [09-01|13:30:43.473] Peer disconnected                        id=QmSSYWEMLxx7UaPjFagffvaXQQ55n4DXkVJUDVgV5kZ4Bx
INFO [09-01|13:30:43.473] Peer disconnected                        id=Qmcu6RYKdTN9g453h3Ju2zwbuxRQzJNumKpRQCHAZo4Xzd
INFO [09-01|13:30:43.834] Peer disconnected                        id=QmYfSfZy9UniuJHexGpT7Xb5WZVSzvs6vA2CCd8m7AZh7q
INFO [09-01|13:30:44.341] Peer disconnected                        id=QmNwz5mrcMq3zrXqfkgaPygCdWnErW9gRi8x9Wvs8aD1Vt
INFO [09-01|13:30:47.606] Selected proposer                        proposer="NOT FOUND"
```
So now he has 0 peers but App works as if he is connected, he is clicking happily and solving flips and submits his answers for short session on time. But he has no connection to any peer.

```shell
INFO [09-01|13:31:30.146] Broadcast ceremony tx                    type=5 hash=0x192fc39238b5ba16f735ee101ac81297c788e4f24a1f9ba77ef3bb4515735d31
```

Only after short session has passed, his node gets connected to one peer, but now it's too late to send answers

```shell
INFO [09-01|13:32:24.575] Peer connected                           id=QmYEmosGrQPcBXPGpn2AFzjqCrx1Dv9RH8EDT8UWJfVUEk inbound=false
```

And at this point he continues solving long session as if nothing happened, he is still happy. But only when validation is over he is faced with sad fact that he had "Late submission" as a result of his short session result, so confusion kicks in and he blames Idena network instead of his connection issues.

As a better user experience maybe it would be good to show notification that connection has been lost so he is aware of it. And if type=5 tx is sent while there are 0 peers and no new peers before short session ends, don't allow him into long session.

**Comment by marcovan123** [comment]
![Idena_01](https://user-images.githubusercontent.com/49187640/133218617-588244c6-3712-4cce-8466-3b64b5f0e1ef.jpg)

I finished the #73 validation and became age 1 before taking the #74 one. 
All of things are okay. 
I believe that the issue is the convergence of the Idena network, because:
- I think that the router was not problem here, because I have used 3G data until now. So internet connection was okay.
- I passed the short session so continued to take the long one, so I think my synchronization for short session was okay.
During the validation, there were any issues with synchronization.

Plz help me to solve the issue. Thanks for your support!

**Comment by aidenaio** [comment]
thanks for the suggestion. this is in works

**Comment by hlolve** [comment]
>     * I think that the router was not problem here, because my friend and I have used 3G connection for validations (my friend passed� 4 validations and I passed 1 validation)� and all of things are okay until now. So internet connection was okay.

In your previous validation you can see you have peers connected and can send the message

 ```shell
INFO [08-12|13:31:49.254] short answers submitting request 
INFO [08-12|13:31:49.269] Broadcast ceremony tx                    type=5 hash=0x0d65bc95f1f29f62bd5004dbb3915ba2c74419334549b1a0b6193ba0fea5a260
INFO [08-12|13:31:49.269] short answers submitting response 
INFO [08-12|13:31:49.271] Sent own tx push                         hash=0x0d65bc95f1f29f62bd5004dbb3915ba2c74419334549b1a0b6193ba0fea5a260
INFO [08-12|13:31:49.272] Sent high priority msg, code 14          id=QmXESdG181Zj7CqHH8TdVay1HtQQohDd3oie4y1VWSWTYx
INFO [08-12|13:31:49.272] Sent high priority msg, code 14          id=QmejqBdEfwF517ZeYZxhz3SPBH5kjQzqnbCM2pcq2dapWK
INFO [08-12|13:31:49.273] Sent high priority msg, code 14          id=QmeNXRTqcYecNFzZTWh7qXNPb2DYJ9bGG8ovnvNTirBSWu
INFO [08-12|13:31:49.273] Sent high priority msg, code 14          id=QmdxHmcfYaGWKu4tXkWhDhq2JfzeQNa9vUH8rnuQkQquiX
INFO [08-12|13:31:49.273] Sent high priority msg, code 14          id=QmQBQ7DFHzTN9M6q72V4GwGfy5FtwV1dC7EPSUt4UuaKFx
INFO [08-12|13:31:49.461] Sent high priority msg, code 14          id=QmbyjRCTkhK5WQZ88aCYMUaQ1dyoSCc3S6yxMMYLpuX1ZB
INFO [08-12|13:31:49.563] long hashes request
 ```

In last validation short answer message couldn't be sent, because the node at that time was offline

 ```shell
INFO [09-01|13:31:30.135] short answers submitting request 
INFO [09-01|13:31:30.146] Broadcast ceremony tx                    type=5 hash=0x192fc39238b5ba16f735ee101ac81297c788e4f24a1f9ba77ef3bb4515735d31
INFO [09-01|13:31:30.147] short answers submitting response 
INFO [09-01|13:31:30.146] Sent own tx push                         hash=0x192fc39238b5ba16f735ee101ac81297c788e4f24a1f9ba77ef3bb4515735d31
INFO [09-01|13:31:30.301] long hashes request
 ```

**Comment by marcovan123** [comment]
> > ```
> > * I think that the router was not problem here, because my friend and I have used 3G connection for validations (my friend passed� 4 validations and I passed 1 validation)� and all of things are okay until now. So internet connection was okay.
> > ```
> 
> In your previous validation you can see you have peers connected and can send the message
> 
> ```shell
> INFO [08-12|13:31:49.254] short answers submitting request 
> INFO [08-12|13:31:49.269] Broadcast ceremony tx                    type=5 hash=0x0d65bc95f1f29f62bd5004dbb3915ba2c74419334549b1a0b6193ba0fea5a260
> INFO [08-12|13:31:49.269] short answers submitting response 
> INFO [08-12|13:31:49.271] Sent own tx push                         hash=0x0d65bc95f1f29f62bd5004dbb3915ba2c74419334549b1a0b6193ba0fea5a260
> INFO [08-12|13:31:49.272] Sent high priority msg, code 14          id=QmXESdG181Zj7CqHH8TdVay1HtQQohDd3oie4y1VWSWTYx
> INFO [08-12|13:31:49.272] Sent high priority msg, code 14          id=QmejqBdEfwF517ZeYZxhz3SPBH5kjQzqnbCM2pcq2dapWK
> INFO [08-12|13:31:49.273] Sent high priority msg, code 14          id=QmeNXRTqcYecNFzZTWh7qXNPb2DYJ9bGG8ovnvNTirBSWu
> INFO [08-12|13:31:49.273] Sent high priority msg, code 14          id=QmdxHmcfYaGWKu4tXkWhDhq2JfzeQNa9vUH8rnuQkQquiX
> INFO [08-12|13:31:49.273] Sent high priority msg, code 14          id=QmQBQ7DFHzTN9M6q72V4GwGfy5FtwV1dC7EPSUt4UuaKFx
> INFO [08-12|13:31:49.461] Sent high priority msg, code 14          id=QmbyjRCTkhK5WQZ88aCYMUaQ1dyoSCc3S6yxMMYLpuX1ZB
> INFO [08-12|13:31:49.563] long hashes request
> ```
> 
> In last validation short answer message couldn't be sent, because the node at that time was offline
> 
> ```shell
> INFO [09-01|13:31:30.135] short answers submitting request 
> INFO [09-01|13:31:30.146] Broadcast ceremony tx                    type=5 hash=0x192fc39238b5ba16f735ee101ac81297c788e4f24a1f9ba77ef3bb4515735d31
> INFO [09-01|13:31:30.147] short answers submitting response 
> INFO [09-01|13:31:30.146] Sent own tx push                         hash=0x192fc39238b5ba16f735ee101ac81297c788e4f24a1f9ba77ef3bb4515735d31
> INFO [09-01|13:31:30.301] long hashes request
> ```

Where can I get the log that you caught ?! 

In my node's local log, all of things are okay during validation, no errors, no warnings, ....
During validation, there was not any requirement of resynchronization (like the attached image) ?! 
![telegram-cloud-photo-size-5-6197314427611622605-y](https://user-images.githubusercontent.com/49187640/133393365-12c16f60-cad8-4dd6-b160-b0c54463e08d.jpg)

**Comment by rioda-org** [comment]
Loosing connections is not presented as an Error in Idena node log, because it is not an Idena Error, it is a situation with your internet connection.
This proposal has exact purpose to update Idena App so that new version will show users in the future that their connection has failed, and it will not let them continue with the validation and the long session. So the confusion will be avoided.

**Comment by rioda-org** [comment]
I will try to explain. Idena programs are still in early phase of development. Everything we (all people in Idena) do is like a testing  a new technology. And over time when someone, like you, experience some problems, that helps out to propose new things to improve the way programs are working.

And since Idena App is not currently in it's final version, it currently has no option to notifiy you about lost connection and to stop you from doing long session.

As you saw, comment from developer, they are allready aware of this and are working to improve it, so some next version can have those options and make experience better.

You can explore other issues that were also identified and need development. Also you can see all past issues that were solved and closed over period of 2 years of development.

**Comment by marcovan123** [comment]
> > In my node's local log, all of things are okay during validation, no errors, no warnings, ....
> 
> And no sent message with short session answer. Where do you see " Sent high priority msg, code 14 " on latest validation log ? Your node was disconnected at moment you clicked submit button
> 
> And the picture you attached is from client log, there were no problem because you are using a local node, and your validation continued because your filps were previously loaded, and then node got connection again.

You mean my attached image ?! After I clicked submit button (11 seconds earlier), you mean that my short session's results wasn't submitted to Idena network successfully ?! 
So could you show me how Idena network evaluated that my short session passed ?! (In fact, I passed 6/6) I don't understand when Idena network thinks a node 'LATE SUBMISSION' ?!  How to evaluate it ?!

<img width="1116" alt="Screen Shot 2021-09-15 at 11 07 20 PM" src="https://user-images.githubusercontent.com/49187640/133469539-c84099d3-e766-4a92-bc49-588db87320e8.png">

**Comment by rioda-org** [comment]
Node needs to send those messages before 13:32. Before short session is over.

**Comment by hlolve** [comment]
> You mean my attached image ?! After I clicked submit button (11 seconds earlier), you mean that my short session's result wasn't submitted to Idena network successfully ?!
> So could you show me how Idena network evaluated that �my short session passed ?! (In fact, I passed 6/6) I don't understand when Idena network thinks a node 'LATE SUBMISSION' ?! How to evaluate it ?!

https://github.com/idena-network/idena-go/discussions/638

This condition failed " Short answers hash message was seen during the short session "

And as you can see in the last image you pasted, time was outside short session time frame, and the node was having problems to sync

**Comment by marcovan123** [comment]
> > You mean my attached image ?! After I clicked submit button (11 seconds earlier), you mean that my short session's result wasn't submitted to Idena network successfully ?!
> > So could you show me how Idena network evaluated that �my short session passed ?! (In fact, I passed 6/6) I don't understand when Idena network thinks a node 'LATE SUBMISSION' ?! How to evaluate it ?!
> 
> [idena-network/idena-go#638](https://github.com/idena-network/idena-go/discussions/638)
> 
> This condition failed " Short answers hash message was seen during the short session "
> 
> And as you can see in the last image you pasted, time was outside short session time frame, and the node was having problems to sync
> 
> And the msg code 14 you are marking in picture, are Short session answers, not Short answers proof

So confused ! You haven't answered the issue that I mentioned. 
We need to ignore the notifications or logs of disconnected peers to clearify the issue.

As I know that if my node had problem to sync, so my short session would failed and I couldn't continue to the long short, right ? You mean that ?!
But in fact, I passed the short session and was allowed to take the long short ? what was the proof to specify my short session's success, then I was allowed to step into the long short ? Plz show me what the short answers proof is in the logs ?!

Thanks!

**Comment by hlolve** [comment]
> So confused ! You haven't answered the issue that I mentioned.

Your node couldn't send short answer proof as i showed you in my first comment

> We need to ignore the notifications or logs of disconnected peers to clearify the issue.

No, that is showing your problem was internet connection

> As I know that if my node has problem to sync, so my short session �will fail and I can't continue to the long short, right ? You mean that ?!

I never said that, read my second comment

> Plz show me what the short answers proof is in the logs ?!

Is in my first comment, and your node never sent because was offline

**Comment by marcovan123** [comment]
> > So confused ! You haven't answered the issue that I mentioned.
> 
> Your node couldn't send short answer proof as i showed you in my first comment
> 
> > We need to ignore the notifications or logs of disconnected peers to clearify the issue.
> 
> No, that is showing your problem was internet connection
> 
> > As I know that if my node has problem to sync, so my short session �will fail and I can't continue to the long short, right ? You mean that ?!
> 
> I never said that, read my second comment
> 
> > Plz show me what the short answers proof is in the logs ?!
> 
> Is in my first comment, and your node never sent because was offline

>Is in my first comment, and your node never sent because was offline
All of things I describe to ask you for this. So why did my short session passed temporarily ?!?! You mean that the process 'the short session was evaluated whether or not done to continue to the long session' is offline on my local node, right ?! 

I hope that you understand my words.

**Comment by hlolve** [comment]
Because the short answer proof must send on time, and evaluated by the network by consensus at the end of validation. At time you sent short answer proof your node was clearly offline.

**Comment by marcovan123** [comment]
> Because the short answer proof must send on time, and evaluated by the network by consensus at the end of validation. At time you sent short answer proof your node was clearly offline.



My friends and I have failed in the short session some times because of the internet connection's error, so we couldn't be allowed to take the long session, and our validation failed :). 

> At time you sent short answer proof your node was clearly offline.
As you said, my node was offline okay, so my node automatically made decision and allowed itself to pass the short session and I could continue to finish my long one ?! :) This thing means that my node was not related to the Idena network during validation ?!?!

Your answer is Unreasonable :) You don't focus on the issue that I mentioned :) I think you don't want to admit the problem of the convergence mechanism in the Idena network :)

**Comment by hlolve** [comment]
My friend, I am trying to help you to not have the same error in next validation. The problem was in your side. If you want on next validation, after start short session, turn off your 3g, or your router and you will have same result.

**Comment by hlolve** [comment]
And if you insist using that bad internet, I also recommend you validate in a shared node. There, you will have more chances to succesful when using bad connections, but shared nodes are not magic, still needs a stable connection.

**Comment by marcovan123** [comment]
> My friend, I am trying to help you to not have the same error in next validation. The problem was in your side. If you want on next validation, after start short session, turn off your 3g, or your router and you will have same result.

>And if you insist using that bad internet, I also recommend you validate in a shared node. There, you will have more chances to succesful when using bad connections, but shared nodes are not magic, still needs a stable connection.

Stupid ?!  sorry but I am forced to call you like this :) Don't trick me and hide the problem :)
fake-sync of the short session :) The Idena is not good enough for IDENTITY SERVICE (the Idena's most important role) :) 

If you're one of Idena developers, after your explainations I understand your poor technical aspect :)

**Comment by hlolve** [comment]
My friend, I am not Idena developer, I am a validated ID that not fail using my own shared node, and help a lot of people to pass validation. But Idena is about people, and always wil have someone that understand and others don't.

**Comment by hlolve** [comment]
I offer you a free access to my shared node in next validation
