### ISSUE TITLE
The Quit button doesn't work. Neither from the main menu nor from the taskbar icon.

### ISSUE THREAD

**Issue by ltraveler** [idena-network/idena-desktop#698]
**Describe the bug**
Can't close idena client using quit button from the main menu or from the taskbar tray icon in Windows 10.

**Module**
In any module

**To Reproduce**
1. Go to Main Menu: Idena -> Quit
Nothing happened.

**Expected behavior**
Idena client has to be closed.

**Environment:**
 - OS: Windows 10 (Version 10.0.19042.1110)
 - Client version 0.27.1
 - Node version 0.27

**Comment by aidenaio** [comment]
should be fixed in #694

**Comment by aidenaio** [comment]
should be fine after the release
