### ISSUE TITLE
Cannot Close idena desktop APP

### ISSUE THREAD

**Issue by JaymenChou** [idena-network/idena-desktop#715]
**Describe the bug**
When i click quit on idena desktop APP, it wont close it and remain on background. Even i force end the task, it comes up again. Is it a bug or the app is doing something else in background? 

**Environment:**
 - OS: Windows 10  64bits  VErsion 20H2
 - Client version [e.g. 0.27.3]

**Comment by aidenaio** [comment]
should be fixed in #728 which is `0.28.1` version and higher
