### ISSUE TITLE
Problem exporting key without password

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-desktop#736]
when exporting the key and entering no password one ends up with this very unhelpful dialog:

![image](https://user-images.githubusercontent.com/111600/142745059-5a363f6b-42c2-4d8d-a9b5-d6c176e55c29.png)

It would be OK to not allow exporting without a password (even though I would prefer if it is possible) - but then there should be some warning/info - not this kind of very unhelpful dialog.
Also IMHO the password should not be cached (I need to actively quit idena to enter a new password)

**Module**
- Settings

**Environment:**
 - OS: linux
 - Node mode: remote
 - Client version 0.27.3
 - Node version 0.28.1

**Comment by aidenaio** [comment]
agree. the input should be validated

**Comment by aidenaio** [comment]
https://github.com/idena-network/idena-desktop/pull/798
