### ISSUE TITLE
Improve reporting rules

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-desktop#863]
These are the current rules:

![image](https://user-images.githubusercontent.com/111600/203802992-bc23302b-aedc-416d-b686-b19a17b2ccac.png)

I think they should also contain Thumbs-up, Wake-up or 2 story flips - or maybe something general/catch-all.

**Comment by midenaio** [comment]
@ligi thanks for the proposal. Reporting rules will be updated starting from epoch `#0100`: https://github.com/idena-network/idena-web/pull/366
